#!/bin/bash
# this script uses jq to parse json results. get it from https://stedolan.github.io/jq/

for region in `aws ec2 describe-regions --region=eu-central-1 --output text | cut -f3`
do
     echo -e "\nListing Instances in region:'$region'..."
     aws ec2 describe-spot-instance-requests --region $region | jq '.SpotInstanceRequests[] | ({InstanceId: .InstanceId, SpotInstanceRequestId: .SpotInstanceRequestId, Type: .Type, CreateTime: .CreateTime, ValidUntil: .ValidUntil, State: .State, Status: .Status.Code, LaunchedAvailabilityZone: .LaunchedAvailabilityZone, InstanceType: .LaunchSpecification.InstanceType, Placement: .LaunchSpecification.Placement, SpotPrice: .SpotPrice})'
done
